use_frameworks!

platform :ios, '8.0'

target 'TestShare_Example' do
  pod 'TestShare', :path => '../'

  target 'TestShare_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
